name: merge-multiarch-images
description: merge multi-arch images based on images digests provided
inputs:
  digest-artifact-prefix:
    description: the prefix of the artifact filename
    default: digest-
  component:
    description: |
      The component name (e.g., policy-server, kubewarden-controller, audit-scanner)
    required: true
  tag:
    description: |
      The tag component in a fully qualified image.
    required: true
  arch:
    description: The list of image architecture for this action to merge (comma-separated)
    default: amd64,arm64
  github-token:
    description: |
      The GitHub token with permission to publish images to ghcr.
    required: true
runs:
  using: composite
  steps:
    - name: Download all digests
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        path: ${{ runner.temp }}/digests
        pattern: ${{ inputs.digest-artifact-prefix}}${{ inputs.component }}-*
        merge-multiple: true
    - name: Install cosign
      uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
    - name: Login to GHCR
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
    - name: Create and push multi-arch manifest for ${{ inputs.component }}
      id: create-manifest
      working-directory: ${{ runner.temp }}/digests
      shell: bash
      run: |
        set -e
        TARGET=""

        ARCHES=$(echo ${{ inputs.arch }} | tr ',' ' ')

        for ARCH in $ARCHES
        do
          TARGET+=" ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}@$(cat ${{ inputs.component }}-$ARCH.txt)"
        done

        # Create the manifest locally
        docker buildx imagetools create \
          -t ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}:${{ inputs.tag }} \
          $TARGET \
          --dry-run > expected-multi-arch-manifest.json

        # Create the manifest and push it
        docker buildx imagetools create \
          -t ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}:${{ inputs.tag }} \
          $TARGET

        # The previous command is NOT printing the digest of the multi-arch manifest, we have to obtain it by
        # fetching it from the OCI registry and **verify** its contents before signing it

        # Fetch the multi arch manifest
        docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}:${{ inputs.tag }} \
          --raw > multi-arch-manifest.json
        multi_arch_manifest_digest="sha256:$(sha256sum multi-arch-manifest.json | awk '{print $1}')"

        # Compare the contents of the manifest we previously computed and the actual one.
        # Use jq to sort the contents and build a compact output (removing useless whitespaces),
        # this is done to ensure the JSON documents have the same structure.
        expected_digest="sha256:$(jq -S -c . expected-multi-arch-manifest.json | sha256sum | awk '{print $1}')"
        actual_digest="sha256:$(jq -S -c . multi-arch-manifest.json | sha256sum | awk '{print $1}')"

        if [ "$expected_digest" != "$actual_digest" ]; then
          echo "Error: digests do not match!"
          exit 1
        fi

        # Sign the multi-arch image manifest using cosign v2 format
        cosign sign --yes --new-bundle-format=false --use-signing-config=false \
          ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}@${multi_arch_manifest_digest}

        # Sign the multi-arch image manifest using cosign v3 format
        cosign sign --yes --new-bundle-format=true --use-signing-config=true \
          ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}@${multi_arch_manifest_digest}

        echo "MULTI_ARCH_MANIFEST_DIGEST=$multi_arch_manifest_digest" >> $GITHUB_ENV

    - name: Verify multi-arch manifest signature
      shell: bash
      run: |
        cosign verify \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity="${{ github.server_url }}/${{ github.workflow_ref }}" \
          ghcr.io/${{ github.repository_owner }}/${{ inputs.component }}@${{ env.MULTI_ARCH_MANIFEST_DIGEST}}
