name: "kwctl-installer"
description: "Install kwctl and includes it inside of PATH"
branding:
  icon: "package"
  color: "blue"
inputs:
  KWCTL_VERSION:
    description: "kwctl release to be installed"
    required: false
    default: v1.22.0
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -e

        INSTALL_DIR=$HOME/.kwctl
        RELEASE_URL="download/${{ inputs.KWCTL_VERSION }}"
        [ "${{ inputs.KWCTL_VERSION }}" == "latest" ] && RELEASE_URL="latest/download"

        mkdir -p $INSTALL_DIR
        curl -sL https://github.com/kubewarden/kwctl/releases/$RELEASE_URL/kwctl-linux-x86_64.zip -o $INSTALL_DIR/kwctl-linux-x86_64.zip
        unzip -o $INSTALL_DIR/kwctl-linux-x86_64.zip -d $INSTALL_DIR
        rm $INSTALL_DIR/kwctl-linux-x86_64.zip

        mv $INSTALL_DIR/kwctl-linux-x86_64 $INSTALL_DIR/kwctl
        chmod 755 $INSTALL_DIR/kwctl
        echo $INSTALL_DIR >> $GITHUB_PATH

        $INSTALL_DIR/kwctl -V
