name: "kubewarden-policy-gh-action-dependencies"
description: "Install all the binaries needed inside of GH action"
branding:
  icon: "package"
  color: "blue"
runs:
  using: "composite"
  steps:
    - name: Install cosign
      uses: sigstore/cosign-installer@v3
    - name: Install kwctl
      uses: kubewarden/github-actions/kwctl-installer@v3.4.3
    - name: Install bats
      uses: mig4/setup-bats@v1.2.0
      with:
        bats-version: 1.11.0
    - name: Install SBOM generator tool
      uses: kubewarden/github-actions/sbom-generator-installer@v3.4.3
    - name: Install SBOM generator tool
      uses: kubewarden/github-actions/binaryen-installer@v3.4.3
