name: 'kubewarden-policy-build-rust'
description: 'Build a rust policy using rust'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  metadata-file:
    description: 'name of the metata file'
    required: false
    default: metadata.yml
  input-wasm:
    description: 'path to the wasm file to be annotated'
    required: true
runs:
  using: "composite"
  steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Prepare Rust environment
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-wasi
    -
      name: Build Wasm module
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target=wasm32-wasi --release
    -
      name: Annotate Wasm module
      shell: bash
      run: |
        kwctl annotate -m ${{ inputs.metadata-file }} -o annotated-policy.wasm ${{ inputs.input-wasm }}
    -
      name: Install SBOM generator tool
      uses: kubewarden/github-actions/sbom-generator-installer@v1
    -
      name: Generate the SBOM files
      shell: bash
      run: |
        spdx-sbom-generator -f json

        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        mv bom-cargo.json policy-sbom.spdx.json
    -
      name: Install cosign
      uses: sigstore/cosign-installer@main
    -
      name: Sign BOM file
      shell: bash
      run: |
        cosign sign-blob --output-certificate policy-sbom.spdx.cert \
          --output-signature policy-sbom.spdx.sig \
          policy-sbom.spdx.json
      env:
        COSIGN_EXPERIMENTAL: 1
    -
      name:  Upload policy SBOM files
      uses: actions/upload-artifact@v3
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.spdx.cert
          policy-sbom.spdx.sig
