name: "opa-installer"
description: "Install opa and add it to PATH"
branding:
  icon: "package"
  color: "blue"
inputs:
  opa-version:
    description: "opa release to be installed"
    required: false
    default: "v0.65.0"
  checksum:
    description: "SHA256 checksum of the opa release binary"
    required: false
    default: "cd6b0b2d762571a746f0261890b155e6dd71cca90dad6b42b6fcf6dd7f619f08"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -euo pipefail

        VERSION="${{ inputs.opa-version }}"
        CHECKSUM="${{ inputs.checksum }}"
        INSTALL_DIR="$HOME/.opa"
        OPA_BINARY="opa_linux_amd64_static"

        mkdir -p "$INSTALL_DIR"

        curl -fsSL "https://github.com/open-policy-agent/opa/releases/download/${VERSION}/${OPA_BINARY}" -o "$INSTALL_DIR/$OPA_BINARY"
        printf "%s  %s\n" "$CHECKSUM" "$INSTALL_DIR/$OPA_BINARY" | sha256sum --check

        mv "$INSTALL_DIR/$OPA_BINARY" "$INSTALL_DIR/opa"
        chmod 755 "$INSTALL_DIR/opa"
        echo "$INSTALL_DIR" >> "$GITHUB_PATH"
