name: "kubewarden-policy-build-go-wasi"
description: "Build a Go policy using the official Go compiler, targetting WASI"
branding:
  icon: "package"
  color: "blue"
inputs:
  generate-sbom:
    required: false
    description: "Generate and sign SBOM files"
    # Boolean input should be compared with string
    # until https://github.com/actions/runner/issues/2238 resolved
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"
    - name: Build Wasm module
      shell: bash
      run: |
        make policy.wasm
    - name: Generate the SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        spdx-sbom-generator -f json

        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        mv bom-go-mod.json policy-sbom.spdx.json
    - name: Annotate Wasm module
      shell: bash
      run: |
        make annotated-policy.wasm
    - name: Sign BOM file
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        cosign sign-blob --yes --output-certificate policy-sbom.spdx.cert \
          --output-signature policy-sbom.spdx.sig \
          policy-sbom.spdx.json
    - name: Upload policy SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.spdx.cert
          policy-sbom.spdx.sig
