name: "kubewarden-policy-build-tinygo"
description: "Build a Go policy using TinyGo"
branding:
  icon: "package"
  color: "blue"
inputs:
  generate-sbom:
    required: false
    description: "Generate and sign SBOM files"
    # Boolean input should be compared with string
    # until https://github.com/actions/runner/issues/2238 resolved
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    # TinyGo requires the official Go compiler to be installed
    # Ensure latest stable release is available, do not rely on what
    # is provided out of the box by  the GH runner
    - name: setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: "1.25"
    - name: Install tinygo
      shell: bash
      run: |
        TINYGO_VERSION="0.39.0"
        TINYGO_CHECKSUM="775f15974e35059c8f3a141266bd9d293b5d556a3e44d5e6356c5602e9f386ab"
        TINYGO_DEB="tinygo_${TINYGO_VERSION}_amd64.deb"
        wget https://github.com/tinygo-org/tinygo/releases/download/v${TINYGO_VERSION}/${TINYGO_DEB}
        echo "${TINYGO_CHECKSUM}  ${TINYGO_DEB}" | sha256sum --check
        sudo dpkg -i ${TINYGO_DEB}
    - name: Build Wasm module
      shell: bash
      run: |
        tinygo build -o policy.wasm -target=wasi -no-debug .
    - name: Generate the SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        syft scan --output spdx-json=policy-sbom.spdx.json \
          --source-name $(yq '.annotations["io.kubewarden.policy.title"] + "-" + .annotations["io.kubewarden.policy.version"]' metadata.yml) \
          --source-version ${{ github.sha }} \
          -vv dir:.
    - name: Annotate Wasm module
      shell: bash
      run: |
        make annotated-policy.wasm

    - name: Sign BOM file
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        cosign sign-blob --yes \
          --new-bundle-format=true --use-signing-config=true \
          --bundle policy-sbom.spdx.jsonl.bundle.sigstore \
          policy-sbom.spdx.json

    - name: Upload policy SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.spdx.jsonl.bundle.sigstore
