name: "kubewarden-policy-build-tinygo"
description: "Build a Go policy using TinyGo"
branding:
  icon: "package"
  color: "blue"
inputs:
  tinygo-version:
    required: true
    description: "Version of tinygo to use"
    default: 0.35.0
  generate-sbom:
    required: false
    description: "Generate and sign SBOM files"
    # Boolean input should be compared with string
    # until https://github.com/actions/runner/issues/2238 resolved
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # TinyGo requires the official Go compiler to be installed
    # Ensure latest stable release is available, do not rely on what
    # is provided out of the box by  the GH runner
    - name: setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"
    - name: Install tinygo
      shell: bash
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v${{ inputs.tinygo-version }}/tinygo_${{ inputs.tinygo-version }}_amd64.deb
        sudo dpkg -i tinygo_${{ inputs.tinygo-version }}_amd64.deb
    - name: Build Wasm module
      shell: bash
      run: |
        tinygo build -o policy.wasm -target=wasi -no-debug .
    - name: Generate the SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        spdx-sbom-generator -f json

        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        mv bom-go-mod.json policy-sbom.spdx.json
    - name: Annotate Wasm module
      shell: bash
      run: |
        make annotated-policy.wasm
    - name: Sign BOM file
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        cosign sign-blob --yes --output-certificate policy-sbom.spdx.cert \
          --output-signature policy-sbom.spdx.sig \
          policy-sbom.spdx.json
    - name: Upload policy SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.spdx.cert
          policy-sbom.spdx.sig
