name: "kubewarden-policy-build-tinygo"
description: "Build a Go policy using TinyGo"
branding:
  icon: "package"
  color: "blue"
inputs:
  tinygo-version:
    required: true
    description: "Version of tinygo to use"
    default: 0.39.0
  generate-sbom:
    required: false
    description: "Generate and sign SBOM files"
    # Boolean input should be compared with string
    # until https://github.com/actions/runner/issues/2238 resolved
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    # TinyGo requires the official Go compiler to be installed
    # Ensure latest stable release is available, do not rely on what
    # is provided out of the box by  the GH runner
    - name: setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: "1.25"
    - name: Install tinygo
      shell: bash
      run: |
        wget https://github.com/tinygo-org/tinygo/releases/download/v${{ inputs.tinygo-version }}/tinygo_${{ inputs.tinygo-version }}_amd64.deb
        sudo dpkg -i tinygo_${{ inputs.tinygo-version }}_amd64.deb
    - name: Build Wasm module
      shell: bash
      run: |
        tinygo build -o policy.wasm -target=wasi -no-debug .
    - name: Generate the SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        # SBOM files should have "sbom" in the name due the CLO monitor
        # https://clomonitor.io/docs/topics/checks/#software-bill-of-materials-sbom
        syft scan --output spdx-json=policy-sbom.spdx.json \
          --source-name $(yq '.annotations["io.kubewarden.policy.title"] + "-" + .annotations["io.kubewarden.policy.version"]' metadata.yml) \
          --source-version ${{ github.sha }} \
          -vv dir:.
    - name: Annotate Wasm module
      shell: bash
      run: |
        make annotated-policy.wasm
    - name: Sign BOM file
      if: ${{ inputs.generate-sbom == 'true' }}
      shell: bash
      run: |
        cosign sign-blob --yes --output-certificate policy-sbom.spdx.cert \
          --output-signature policy-sbom.spdx.sig \
          policy-sbom.spdx.json
    - name: Upload policy SBOM files
      if: ${{ inputs.generate-sbom == 'true' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: policy-sbom
        path: |
          policy-sbom.spdx.json
          policy-sbom.spdx.cert
          policy-sbom.spdx.sig
