name: 'kubewarden-policy-release'
description: 'Release a Kubewarden policy'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  annotated-wasm:
    description: 'name of the annotated wasm file'
    required: false
    default: annotated-policy.wasm
  oci-target:
    required: true
    type: string
  GITHUB_TOKEN:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.GITHUB_TOKEN }}
    -
      name: Publish Wasm policy artifact to OCI registry with the 'latest' tag
      shell: bash
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        set -ex
        echo Pushing policy to OCI container registry
        IMMUTABLE_REF=$(kwctl push -o json ${{ inputs.annotated-wasm }} ${{ inputs.oci-target }}:latest | jq -r .immutable_ref)

        echo Keyless signing of policy using cosign
        cosign sign --yes ${IMMUTABLE_REF}
    -
      name: Publish Wasm policy artifact to OCI registry with the version tag and 'latest'
      shell: bash
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      env:
        COSIGN_EXPERIMENTAL: 1
      run: |
        set -ex
        export OCI_TAG=$(echo $GITHUB_REF | sed -e "s|refs/tags/||")

        echo Pushing policy to OCI container registry
        IMMUTABLE_REF=$(kwctl push -o json ${{ inputs.annotated-wasm }} ${{ inputs.oci-target }}:${OCI_TAG} | jq -r .immutable_ref)

        echo Keyless signing of policy using cosign
        cosign sign --yes ${IMMUTABLE_REF}
    -
      name: Create release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}
        files: |
          policy.wasm
          policy-sbom.spdx.json
          policy-sbom.spdx.cert
          policy-sbom.spdx.sig
