name: "kubewarden-policy-release"
description: "Release a Kubewarden policy"
branding:
  icon: "package"
  color: "blue"
inputs:
  annotated-wasm:
    description: "name of the annotated wasm file"
    required: false
    default: annotated-policy.wasm
  oci-target:
    description: "OCI target repository for the resulting policy artifact"
    required: true
    type: string
  GITHUB_TOKEN:
    description: "GitHub token to login into ghcr.io"
    required: true
    type: string
  policy-working-dir:
    description: "working directory of the policy. Useful for repos with policies in folders"
    required: false
    type: string
    default: .
  policy-version:
    description: "release version of the policy without `v` prefix. E.g: 0.1.0"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.GITHUB_TOKEN }}
    - name: Publish Wasm policy artifact to OCI registry with the 'latest' tag
      shell: bash
      if: ${{ startsWith(github.ref, 'refs/heads/') }}
      run: |
        set -ex
        echo Pushing :latest policy to OCI container registry
        IMMUTABLE_REF=$(kwctl push -o json ${{ inputs.annotated-wasm }} ${{ inputs.oci-target }}:latest | jq -r .immutable_ref)

        echo Keyless signing of policy using cosign
        cosign sign --yes ${IMMUTABLE_REF}
    - name: Publish Wasm policy artifact to OCI registry with the version tag and 'latest'
      shell: bash
      if: ${{ ! startsWith(github.ref, 'refs/heads/') }}
      working-directory: ${{ inputs.policy-working-dir }}
      run: |
        set -ex
        export OCI_TAG="v${{ inputs.policy-version }}"

        echo Pushing tagged policy to OCI container registry
        IMMUTABLE_REF=$(kwctl push -o json ${{ inputs.annotated-wasm }} ${{ inputs.oci-target }}:${OCI_TAG} | jq -r .immutable_ref)

        echo Keyless signing of policy using cosign
        cosign sign --yes ${IMMUTABLE_REF}
    - name: Get release ID from the release created by release drafter
      if: ${{ ! startsWith(github.ref, 'refs/heads/') }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          let releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
          });
          for (const release of releases.data) {
            if (release.draft) {
                    core.info(release)
                    core.exportVariable('RELEASE_ID', release.id)
                    return
            }
          }
          core.setFailed(`Draft release not found`)
    - name: Upload release assets
      if: ${{ ! startsWith(github.ref, 'refs/heads/') }}
      id: upload_release_assets
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          let fs = require('fs');
          let path = require('path');

          let files = [
            'policy.wasm',
            'policy-sbom.spdx.json',
            'policy-sbom.spdx.cert',
            'policy-sbom.spdx.sig']
          const {RELEASE_ID} = process.env

          for (const file of files) {
            let file_data = fs.readFileSync(file);

            let response = await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: `${RELEASE_ID}`,
              name: path.basename(file),
              data: file_data,
            });
          }
    - name: Publish release
      if: ${{ ! startsWith(github.ref, 'refs/heads/') }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const {RELEASE_ID} = process.env
          const TAG_NAME = "${{ github.ref_name }}";
          isPreRelease = ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}
          github.rest.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: `${RELEASE_ID}`,
            draft: false,
            tag_name: TAG_NAME,
            name: TAG_NAME,
            prerelease: isPreRelease,
            make_latest: !isPreRelease
          });
