name: 'kubewarden-check-artifacthub'
description: 'Check that artifacthub-pkg.yml is up-to-date'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  version:
    description: 'version string to use in artifacthub-plg.yml'
    required: true
    type: string
    default: false
runs:
  using: "composite"
  steps:
    -
      name: Checkout code
      uses: actions/checkout@v3
    -
      name: Check that artifacthub-pkg.yml is up-to-date
      shell: bash
      run: |
        rm artifacthub-pkg.yml # force recreation of file
        make artifacthub-pkg.yml VERSION=${{ inputs.version }}
        git diff \
          --ignore-matching-lines '^createdAt'\
          --exit-code artifacthub-pkg.yml || \
          (echo; echo "There are differences in artifacthub-pkg.yml that have to be checked in"; exit 1)
