name: "binaryen-installer"
description: "Install binaryen and includes it inside of PATH"
branding:
  icon: "package"
  color: "blue"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -e

        VERSION="116"
        CHECKSUM="c55b74f3109cdae97490faf089b0286d3bba926bb6ea5ed00c8c784fc53718fd"
        INSTALL_DIR=$HOME/.binaryen

        mkdir -p $INSTALL_DIR

        curl -sL https://github.com/WebAssembly/binaryen/releases/download/version_${VERSION}/binaryen-version_${VERSION}-x86_64-linux.tar.gz -o $INSTALL_DIR/binaryen.tar.gz
        echo "${CHECKSUM}  $INSTALL_DIR/binaryen.tar.gz" | sha256sum --check
        tar xvf $INSTALL_DIR/binaryen.tar.gz -C $INSTALL_DIR
        mv $INSTALL_DIR/binaryen-version_${VERSION}/bin/* $INSTALL_DIR
        rm $INSTALL_DIR/binaryen.tar.gz
        rm -rf $INSTALL_DIR/binaryen-version_${VERSION}

        echo $INSTALL_DIR >> $GITHUB_PATH
