name: Tests and linters

on:
  workflow_call:
    inputs:
      policy-working-dir:
        description: "working directory of the policy. Useful for repos with policies in folders"
        required: false
        type: string
        default: .
    secrets: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install opa
        uses: kubewarden/github-actions/opa-installer@1a674c5c7f808bbe48765e5f9a01c6818a3642ac
      - name: Run unit tests
        working-directory: ${{ inputs.policy-working-dir }}
        run: make test
