name: Build and release a Kubewarden policy written in Go

on:
  workflow_call:
    inputs:
      oci-target:
        type: string
        required: true
    secrets:
      workflow-pat:
        description: "Github Personal Access Token (PAT) that can trigger workflow-dispatch"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install dependencies
        uses: kubewarden/github-actions/policy-gh-action-dependencies@v1
      -
        name: Build and annotate policy
        uses: kubewarden/github-actions/policy-build-go@v1
      -
        name: Run e2e tests
        run: |
          make e2e-tests
      -
        name: Release
        uses: kubewarden/github-actions/policy-release@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          oci-target: ${{ inputs.oci-target }}
          workflow-pat: ${{ secrets.workflow-pat }}
