name: 'crane-installer'
description: 'Install crane and includes it inside of PATH'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #!/bin/bash
        set -e

        VERSION="0.15.2"
        CHECKSUM="bd5f72ae96373ac640679a6108280b6d76698773ca21f293ae30cc17413e2ad1"
        INSTALL_DIR=$HOME/.crane

        mkdir -p $INSTALL_DIR

        curl -sL https://github.com/google/go-containerregistry/releases/download/v${VERSION}/go-containerregistry_Linux_x86_64.tar.gz -o $INSTALL_DIR/crane.tar.gz
        echo "${CHECKSUM}  $INSTALL_DIR/crane.tar.gz" | sha256sum --check
        tar xvf $INSTALL_DIR/crane.tar.gz -C $INSTALL_DIR
        rm $INSTALL_DIR/crane.tar.gz

        echo $INSTALL_DIR >> $GITHUB_PATH

